### ISSUE TITLE
[Feature request] npm package

### ISSUE THREAD

**Issue by kfreiman** [amka/quill-focus#1]
Thanks for library and good idea! 
It would be great to have possibility install it through the npm or yarn.

**Comment by amka** [comment]
Hello! Thanks you for this good Idea! Never did it before  🤔  so I'll take some time to realize how to deal with it.

**Comment by paolavness** [comment]
Yeah awesome idea!

**Comment by amka** [comment]
Sorry for late update. Finally got it.
Updated README available.
